// Generated by CoffeeScript 1.6.2
var Batch, coffeescript, fs, init, path;

fs = require('fs');

path = require('path');

Batch = require('batch');

init = require('./utils').init;

coffeescript = require('coffee-script');

module.exports = function(builder) {
  return builder.hook('before scripts', function(pkg, fn) {
    var batch, scripts;

    scripts = pkg.conf.coffee;
    if (!scripts) {
      return fn();
    }
    batch = new Batch();
    if (!pkg.conf.scripts) {
      batch.push(function(done) {
        init(pkg, 'scripts');
        return done();
      });
    }
    scripts.forEach(function(file) {
      return batch.push(function(done) {
        var coffee, coffeefile, js, jsfile;

        coffeefile = pkg.path(file) + '.coffee';
        jsfile = "" + file + ".js";
        coffee = fs.readFileSync(coffeefile, 'utf8');
        js = coffeescript.compile(coffee, {
          bare: true
        });
        pkg.addFile('scripts', jsfile, js);
        return done();
      });
    });
    return batch.end(fn);
  });
};
