// Generated by CoffeeScript 1.6.2
var Builder, coffee, component, fs, jade, mkdir, path, styl, utils, write;

fs = require('fs');

path = require('path');

component = require('component');

utils = component.utils;

jade = require('./jade');

styl = require('./styl');

coffee = require('./coffeec');

mkdir = require('component/node_modules/mkdirp');

Builder = require('component/node_modules/component-builder');

write = fs.writeFileSync;

Builder.prototype.buildAliases = require('./utils').buildAliases;

module.exports = function(req, res, next) {
  var builder, conf, cwd, out;

  out = 'build';
  mkdir.sync(out);
  cwd = process.cwd();
  builder = new Builder(cwd);
  conf = require(cwd + '/component.json');
  builder.addLookup(conf.paths);
  builder.copyAssetsTo(out);
  builder.use(styl);
  builder.use(jade);
  builder.use(coffee);
  return builder.build(function(err, res) {
    if (err) {
      utils.fatal(err.message);
    }
    write('build/build.js', res.require + res.js);
    write('build/build.css', res.css.trim());
    return next();
  });
};
