// Generated by CoffeeScript 1.6.2
var Batch, addConfProperty, fs, jade, path, str2js;

fs = require('fs');

jade = require('jade');

path = require('path');

Batch = require('batch');

addConfProperty = require('./utils').addConfProperty;

str2js = require('string-to-js');

module.exports = function(builder) {
  return builder.hook('before scripts', function(pkg, fn) {
    var batch, templates;

    templates = pkg.config.jade;
    if (!templates) {
      return fn();
    }
    batch = new Batch();
    if (!pkg.config.scripts) {
      batch.push(function(done) {
        addConfProperty(pkg, 'scripts');
        return done();
      });
    }
    templates.forEach(function(file) {
      return batch.push(function(done) {
        var jadefile, js, jsfile, str;

        jadefile = pkg.path(file) + '.jade';
        jsfile = "" + file + ".js";
        str = fs.readFileSync(jadefile, 'utf8');
        js = jade.compile(str, {
          filename: jadefile
        });
        pkg.addFile('scripts', jsfile, str2js(js()));
        return done();
      });
    });
    return batch.end(fn);
  });
};
