// Generated by CoffeeScript 1.6.2
var Batch, fs, init, nib, path, stylus;

fs = require('fs');

nib = require('nib');

path = require('path');

Batch = require('batch');

stylus = require('stylus');

init = require('./utils').init;

module.exports = function(builder) {
  return builder.hook('before styles', function(pkg, fn) {
    var batch, styles;

    styles = pkg.conf.styl;
    if (!styles) {
      return fn();
    }
    batch = new Batch();
    if (!pkg.conf.styles) {
      batch.push(function(done) {
        init(pkg, 'styles');
        return done();
      });
    }
    styles.forEach(function(file) {
      return batch.push(function(done) {
        var cssfile, styl, stylfile;

        stylfile = pkg.path(file) + '.styl';
        cssfile = "" + file + ".css";
        styl = fs.readFileSync(stylfile, 'utf8');
        return stylus(styl).set('include css', true).set('filename', stylfile).use(nib()).render(function(err, css) {
          pkg.addFile('styles', cssfile, css);
          return done();
        });
      });
    });
    return batch.end(fn);
  });
};
